Updates

diff --git a/Softwares/astrodepth_prior_extraction_photometry b/Softwares/astrodepth_prior_extraction_photometry
--- a/Softwares/astrodepth_prior_extraction_photometry
+++ b/Softwares/astrodepth_prior_extraction_photometry
@@ -29,6 +29,7 @@ usage() {
     echo "    # ./output_dir/output_name/fit_0.result                 -- contains the position-fixed point-source galfit photometry on the science image. "
     echo "    # ./output_dir/output_name/fit_1.result                 -- contains the position-varied point-source galfit photometry on the science image. "
     echo "    # ./output_dir/output_name/fit_2.result                 -- contains the position-varied Gaussian-source galfit photometry on the science image. "
+    echo "    # ./output_dir/output_name/fit_3.result                 -- contains the position-varied Sersic-source galfit photometry on the science image. "
     echo "    # ./output_dir/output_name/fit_*.*                      -- internal galfit fitting files. "
     echo ""
     echo ""
@@ -36,7 +37,11 @@ usage() {
 
 # Check current directory
 AstroDepth_ScriptDir=$(dirname ${BASH_SOURCE[0]})
+if [[ $(uname) == "Darwin" ]]; then
+AstroDepth_CurrrentDir=$(pwd)
+else
 AstroDepth_CurrrentDir=$(pwd -P)
+fi
 
 # Check necessary scripts
 if [[ ! -f "$AstroDepth_ScriptDir/sm" || ! -f "$AstroDepth_ScriptDir/astrodepth_command_line_arguments" ]]; then
@@ -60,6 +65,11 @@ fi
 #    usage
 #    exit
 #fi
+
+# Check
+#echo "AstroDepth_INP_STEPS = ${AstroDepth_INP_STEPS[@]}"
+#echo "AstroDepth_INP_UNLOCK = ${AstroDepth_INP_UNLOCK[@]}"
+#echo "AstroDepth_INP_OVERWRITE = ${AstroDepth_INP_OVERWRITE[@]}"
 
 # Check output directory
 if [[ ${#AstroDepth_INP_OUTPUT_DIR[@]} -eq 0 ]]; then
@@ -489,7 +499,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                     exit 1
                 fi
             else
-                echo "Found existing \"getpix.txt\"! We will not overwrite it without \"-overwrite go_getpix\" option!"
+                echo "Found existing \"getpix.txt\"! We will not overwrite it unless given \"-overwrite go_getpix\" option!"
             fi
             # 
             if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"getpix"* || ! -f "getpix.result" ]]; then
@@ -503,7 +513,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                     exit 1
                 fi
             else
-                echo "Found existing \"getpix.result\"! We will not overwrite it without \"-overwrite getpix\" option!"
+                echo "Found existing \"getpix.result\"! We will not overwrite it unless given \"-overwrite getpix\" option!"
             fi
             # 
             #echo "Done!"
@@ -531,7 +541,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     # 
     # 
     # now run galfit on negative image
-    if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "negative"; then
+    if [[ " ${AstroDepth_INP_STEPS[@]} " =~ " negative " ]] && [[ ! " ${AstroDepth_INP_STEPS[@]} " =~ " -negative " ]]; then
         # 
         if [[ ! -f "astrodepth_lock_negative" || "${AstroDepth_INP_UNLOCK[@]}" == *"negative"* ]]; then
             # 
@@ -550,7 +560,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"getpix_on_negative_image.txt\"! We will not overwrite it without \"-overwrite go_getpix\" option!"
+                    echo "Found existing \"getpix_on_negative_image.txt\"! We will not overwrite it unless given \"-overwrite go_getpix\" option!"
                 fi
                 # 
                 if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"negative"* || ! -f "getpix_on_negative_image.result" ]]; then
@@ -564,7 +574,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"getpix_on_negative_image.result\"! We will not overwrite it without \"-overwrite getpix\" option!"
+                    echo "Found existing \"getpix_on_negative_image.result\"! We will not overwrite it unless given \"-overwrite getpix\" option!"
                 fi
                 # 
                 #echo "Done!"
@@ -585,7 +595,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"fit_n0.fits\"! We will not overwrite it without \"-overwrite negative\" option!"
+                    echo "Found existing \"fit_n0.fits\"! We will not overwrite it unless given \"-overwrite negative\" option!"
                 fi
                 if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"negative"* || ! -f "fit_n1.fits" ]]; then
                     echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_n1\""
@@ -598,7 +608,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"fit_n1.fits\"! We will not overwrite it without \"-overwrite negative\" option!"
+                    echo "Found existing \"fit_n1.fits\"! We will not overwrite it unless given \"-overwrite negative\" option!"
                 fi
                 if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"negative"* || ! -f "fit_n2.fits" ]]; then
                     echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_n2\""
@@ -611,7 +621,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"fit_n2.fits\"! We will not overwrite it without \"-overwrite negative\" option!"
+                    echo "Found existing \"fit_n2.fits\"! We will not overwrite it unless given \"-overwrite negative\" option!"
                 fi
                 if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"negative"* || ! -f "final_on_negative_image.result" ]]; then
                     echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_final_on_negative_image\""
@@ -624,7 +634,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"final_on_negative_image.result\"! We will not overwrite it without \"-overwrite final_on_negative_image\" option!"
+                    echo "Found existing \"final_on_negative_image.result\"! We will not overwrite it unless given \"-overwrite final_on_negative_image\" option!"
                 fi
                 #echo "Done!"
             else
@@ -642,7 +652,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     # 
     # 
     # now run galfit on input image
-    if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "galfit"; then
+    if [[ " ${AstroDepth_INP_STEPS[@]} " =~ " galfit " ]] && [[ ! " ${AstroDepth_INP_STEPS[@]} " =~ " -galfit " ]]; then
         # 
         if [[ ! -f "astrodepth_lock_galfit" || "${AstroDepth_INP_UNLOCK[@]}" == *"galfit"*  ]]; then
             # 
@@ -661,7 +671,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"fit_0.fits\"! We will not overwrite it without \"-overwrite galfit\" option!"
+                    echo "Found existing \"fit_0.fits\"! We will not overwrite it unless given \"-overwrite galfit\" option!"
                 fi
                 if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"galfit"* || ! -f "fit_1.fits" ]]; then
                     echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_1\""
@@ -674,7 +684,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"fit_1.fits\"! We will not overwrite it without \"-overwrite galfit\" option!"
+                    echo "Found existing \"fit_1.fits\"! We will not overwrite it unless given \"-overwrite galfit\" option!"
                 fi
                 #echo "Done!"
             else
@@ -693,7 +703,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     # 
     # 
     # now run galfit with gaussian source model
-    if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "gaussian"; then
+    if [[ " ${AstroDepth_INP_STEPS[@]} " =~ " gaussian " ]] && [[ ! " ${AstroDepth_INP_STEPS[@]} " =~ " -gaussian " ]]; then
         # 
         if [[ ! -f "astrodepth_lock_gaussian" || "${AstroDepth_INP_UNLOCK[@]}" == *"gaussian"*  ]]; then
             # 
@@ -712,7 +722,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"fit_2.fits\"! We will not overwrite it without \"-overwrite gaussian\" option!"
+                    echo "Found existing \"fit_2.fits\"! We will not overwrite it unless given \"-overwrite gaussian\" option!"
                 fi
                 # 
                 #<20170626># additional check
@@ -744,8 +754,60 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     # 
     # 
     # 
+    # now run galfit with sersic source model
+    if [[ " ${AstroDepth_INP_STEPS[@]} " =~ " sersic " ]] && [[ ! " ${AstroDepth_INP_STEPS[@]} " =~ " -sersic " ]]; then
+        # 
+        if [[ ! -f "astrodepth_lock_sersic" || "${AstroDepth_INP_UNLOCK[@]}" == *"sersic"*  ]]; then
+            # 
+            touch "astrodepth_lock_sersic"
+            # 
+            # now we run galfit in sci image with sersic models
+            if [[ ! -f "No_catalog_source_within_image" && ! -f "No_catalog_source_with_enough_getpix_SNR" ]]; then
+                if [[ ! -f "fit_3.fits" ]] || [[ " ${AstroDepth_INP_OVERWRITE[@]} " =~ " sersic " ]]; then
+                    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_3\""
+                    echo "macro read astrodepth_go_galfit.sm go_galfit_3" | sm > "astrodepth_go_galfit_3.log"
+                    # check output successful or not
+                    if [[ ! -f "fit_3.fits" ]]; then 
+                        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_3\"! Sorry!"
+                        echo "Log file: \"astrodepth_go_galfit_3.log\""; cat "astrodepth_go_galfit_3.log"
+                        rm "astrodepth_lock_sersic"
+                        exit 1
+                    fi
+                else
+                    echo "Found existing \"fit_3.fits\"! We will not overwrite it unless given \"-overwrite sersic\" option!"
+                fi
+                # 
+                #<20170626># additional check
+                #if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"final"* || ! -f "fit_3.result.ra.dec.f.df.snr.id" ]]; then
+                #    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_fit_3\""
+                #    echo "macro read astrodepth_go_galfit.sm print_result_fit_3" | sm > "astrodepth_go_galfit_print_result_fit_3.log"
+                #    # check output successful or not
+                #    if [[ ! -f "fit_3.result.ra.dec.f.df.snr.id" ]]; then 
+                #        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_fit_3\"! Sorry!"
+                #        echo "Log file: \"astrodepth_go_galfit_print_result_fit_3.log\""; cat "astrodepth_go_galfit_print_result_fit_3.log"
+                #        rm "astrodepth_lock_final"
+                #        exit 1
+                #    fi
+                #fi
+                # 
+                #echo "Done!"
+            else
+                echo "No catalog source within image! Skip and continue!"
+            fi
+            # 
+            rm "astrodepth_lock_sersic"
+            # 
+            date +"%Y-%m-%d %Hh%Mm%Ss %Z" > "astrodepth_done_sersic"
+        fi
+    fi
+    # 
+    # 
+    # 
+    # 
+    # 
+    # 
     # now run supermongo script to get "final.result" (the file containing Nfit and Ndet)
-    if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "final"; then
+    if [[ " ${AstroDepth_INP_STEPS[@]} " =~ " final " ]] && [[ ! " ${AstroDepth_INP_STEPS[@]} " =~ " -final " ]]; then
         # 
         if [[ ! -f "astrodepth_lock_final" || "${AstroDepth_INP_UNLOCK[@]}" == *"final"*  ]]; then
             # 
@@ -764,7 +826,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                         exit 1
                     fi
                 else
-                    echo "Found existing \"final.result\"! We will not overwrite it without \"-overwrite final\" option!"
+                    echo "Found existing \"final.result\"! We will not overwrite it unless given \"-overwrite final\" option!"
                 fi
                 #echo "Done!"
             else
