Updates

diff --git a/Softwares/astrodepth_prior_extraction_photometry b/Softwares/astrodepth_prior_extraction_photometry
--- a/Softwares/astrodepth_prior_extraction_photometry
+++ b/Softwares/astrodepth_prior_extraction_photometry
@@ -571,6 +571,18 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
                 else
                     echo "Found existing \"fit_n2.fits\"! We will not overwrite it without \"-overwrite negative\" option!"
                 fi
+                if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"negative"* || ! -f "final_on_negative_image.result" ]]; then
+                    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_final_on_negative_image\""
+                    echo "macro read astrodepth_go_galfit.sm print_result_final_on_negative_image" | sm > "astrodepth_go_galfit_print_result_final_on_negative_image.log"
+                    # check output successful or not
+                    if [[ ! -f "final_on_negative_image.result" ]]; then 
+                        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_final_on_negative_image\"! Sorry!"
+                        echo "Log file: \"astrodepth_go_galfit_print_result_final_on_negative_image.log\""; cat "astrodepth_go_galfit_print_result_final_on_negative_image.log"
+                        exit 1
+                    fi
+                else
+                    echo "Found existing \"final_on_negative_image.result\"! We will not overwrite it without \"-overwrite final_on_negative_image\" option!"
+                fi
                 #echo "Done!"
             else
                 echo "No catalog source within image! Skip and continue!"
