Updates

diff --git a/Softwares/astrodepth_prior_extraction_photometry b/Softwares/astrodepth_prior_extraction_photometry
--- a/Softwares/astrodepth_prior_extraction_photometry
+++ b/Softwares/astrodepth_prior_extraction_photometry
@@ -393,7 +393,7 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
         fi
         # 
         # get pixnoise
-        if [[ 1 == 1 || ! -f "image_sci_pixnoise.txt" ]]; then
+        if [[ ! -f "image_sci_pixnoise.txt" ]]; then
             tmp_pixel_statistics_txt=$(readlink -f "${AstroDepth_INP_IMAGE_SCI[j]}" | sed -e 's/\.cut_[^\.]*//g')".pixel.statistics.txt"
             if [[ -f "$tmp_pixel_statistics_txt" ]]; then
                 cat "$tmp_pixel_statistics_txt" | grep "Gaussian_sigma =" | perl -p -e 's/(.*) *= *(.*)/\2/g' > "image_sci_pixnoise.txt"
@@ -402,13 +402,13 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
             fi
         fi
         # 
-        # now we run photometry in Scoville way, i.e. measure peak and total flux within a radius=1.5 arcsec circle for each prior source
+        # copy supermongo script for "getpix"
         if [[ 1 == 1 || ! -f "astrodepth_go_getpix.sm" ]]; then
             echo "Preparing Supermongo script \"astrodepth_go_getpix.sm\" and necessary files for running getpix"
             cp "$AstroDepth_ScriptDir/astrodepth_prior_extraction_photometry_go_getpix.sm" "astrodepth_go_getpix.sm"
         fi
         # 
-        # now we run photometry in Scoville way, i.e. measure peak and total flux within a radius=1.5 arcsec circle for each prior source
+        # double check 
         if [[ ! -f "astrodepth_go_getpix.sm" ]]; then
             echo "***************************************************"
             echo "Error! Failed to write \"astrodepth_go_getpix.sm\"!"
@@ -416,20 +416,39 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
             exit 1
         fi
         # 
-        # make supermongo script and execute galfit
+        # copy supermongo script for "galfit"
         if [[ 1 == 1 || ! -f "astrodepth_go_galfit.sm" ]]; then
             echo "Preparing Supermongo script \"astrodepth_go_galfit.sm\" and necessary files for running galfit"
             cp "$AstroDepth_ScriptDir/astrodepth_prior_extraction_photometry_go_galfit.sm" "astrodepth_go_galfit.sm"
         fi
+        # double check 
+        if [[ ! -f "astrodepth_go_galfit.sm" ]]; then
+            echo "***************************************************"
+            echo "Error! Failed to write \"astrodepth_go_galfit.sm\"!"
+            echo "***************************************************"
+            exit 1
+        fi
         # 
-        if [[ ! -f "No_catalog_source_within_image" ]]; then
-            if [[ ! -f "getpix.txt" ]]; then
-                echo "Running Supermongo script \"astrodepth_go_getpix.sm\" subroutine go_getpix"
-                echo "macro read astrodepth_go_getpix.sm go_getpix" | "$AstroDepth_ScriptDir/sm" > "astrodepth_go_getpix.log"
+        # now we run photometry in Scoville way, i.e. measure peak and total flux within a radius=1.5 arcsec circle for each prior source
+        if [[ 1 == 1 || ! -f "No_catalog_source_within_image" ]]; then
+            if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"go_getpix"* || ! -f "getpix.txt" ]]; then
+                echo "Running Supermongo script \"astrodepth_go_getpix.sm\" subroutine \"go_getpix\""
+                echo "macro read astrodepth_go_getpix.sm go_getpix" | sm > "astrodepth_go_getpix.log"
                 # check output successful or not
                 if [[ ! -f "No_catalog_source_within_image" && ! -f "getpix.txt" ]]; then 
                     echo "Error! Failed to run Supermongo script \"astrodepth_go_getpix.sm\" subroutine go_getpix! Sorry!"
                     echo "Log file: \"astrodepth_go_getpix.log\""; cat "astrodepth_go_getpix.log"
+                    exit 1
+                fi
+            fi
+            # 
+            if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"getpix"* || ! -f "getpix.result" ]]; then
+                echo "Running Supermongo script \"astrodepth_go_getpix.sm\" subroutine \"print_result\""
+                echo "macro read astrodepth_go_getpix.sm print_result" | sm > "astrodepth_go_getpix_print_result.log"
+                # check output successful or not
+                if [[ ! -f "No_catalog_source_within_image" && ! -f "getpix.result" ]]; then 
+                    echo "Error! Failed to run Supermongo script \"astrodepth_go_getpix.sm\" subroutine \"print_result\"! Sorry!"
+                    echo "Log file: \"astrodepth_go_getpix_print_result.log\""; cat "astrodepth_go_getpix_print_result.log"
                     exit 1
                 fi
             fi
@@ -443,6 +462,64 @@ for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
     fi
     
 done
+
+
+
+
+
+
+
+# 
+# 
+# Loop again for further steps
+# 
+# 
+if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "negative"; then
+    #echo ""; echo ""; echo ""
+    echo "Continue further steps: negative"
+    #echo ""; echo ""; echo ""
+    # 
+    # 
+    for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
+        # 
+        # 
+        # Check output name
+        if [[ $j -ge ${#AstroDepth_INP_OUTPUT_NAME[@]} ]]; then
+            AstroDepth_OutputName="astrodepth_image_${j}_galfit"
+        else
+            AstroDepth_OutputName=${AstroDepth_INP_OUTPUT_NAME[j]}
+        fi
+        # 
+        # 
+        # cd 
+        if [[ 1 == 1 ]]; then
+            # 
+            cd "$AstroDepth_OutputDir/$AstroDepth_OutputName/"
+            # 
+            # now we run galfit in negative image
+            if [[ ! -f "No_catalog_source_within_image" ]]; then
+                if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"negative"* || ! -f "fit_n1.fits" ]]; then
+                    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_n1\""
+                    echo "macro read astrodepth_go_galfit.sm go_galfit_n1" | sm > "astrodepth_go_galfit_n1.log"
+                    # check output successful or not
+                    if [[ ! -f "No_catalog_source_within_image" && ! -f "fit_n1.fits" ]]; then 
+                        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_n1\"! Sorry!"
+                        echo "Log file: \"astrodepth_go_galfit_n1.log\""; cat "astrodepth_go_galfit_n1.log"
+                        exit 1
+                    fi
+                fi
+                # 
+                echo "Done!"
+            else
+                echo "No catalog source within image! Skip and continue!"
+            fi
+            # 
+            cd "$AstroDepth_CurrrentDir"
+        fi
+        
+    done
+    
+fi
 
 
 
@@ -456,71 +533,61 @@ done
 # 
 # 
 if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "galfit"; then
-    echo ""; echo ""; echo ""
+    #echo ""; echo ""; echo ""
     echo "Continue further steps: galfit"
-    echo ""; echo ""; echo ""
-else
-    exit
-fi
-# 
-# 
-for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
+    #echo ""; echo ""; echo ""
     # 
     # 
-    # Check output name
-    if [[ $j -ge ${#AstroDepth_INP_OUTPUT_NAME[@]} ]]; then
-        AstroDepth_OutputName="astrodepth_image_${j}_galfit"
-    else
-        AstroDepth_OutputName=${AstroDepth_INP_OUTPUT_NAME[j]}
-    fi
-    # 
-    # 
-    # cd 
-    if [[ 1 == 1 ]]; then
+    for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
         # 
-        cd "$AstroDepth_OutputDir/$AstroDepth_OutputName/"
         # 
-        if [[ ! -f "No_catalog_source_within_image" ]]; then
-            if [[ ! -f "fit_n1.fits" ]]; then
-                echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_n1"
-                echo "macro read astrodepth_go_galfit.sm go_galfit_n1" | "$AstroDepth_ScriptDir/sm" > "astrodepth_go_galfit_n1.log"
-                # check output successful or not
-                if [[ ! -f "No_catalog_source_within_image" && ! -f "fit_n1.fits" ]]; then 
-                    echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_n1! Sorry!"
-                    echo "Log file: \"astrodepth_go_galfit_n1.log\""; cat "astrodepth_go_galfit_n1.log"
-                    exit 1
-                fi
-            fi
-            if [[ ! -f "fit_0.fits" ]]; then
-                echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_0"
-                echo "macro read astrodepth_go_galfit.sm go_galfit_0" | "$AstroDepth_ScriptDir/sm" > "astrodepth_go_galfit_0.log"
-                # check output successful or not
-                if [[ ! -f "No_catalog_source_within_image" && ! -f "fit_0.fits" ]]; then 
-                    echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_0! Sorry!"
-                    echo "Log file: \"astrodepth_go_galfit_0.log\""; cat "astrodepth_go_galfit_0.log"
-                    exit 1
-                fi
-            fi
-            if [[ ! -f "fit_1.fits" ]]; then
-                echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_1"
-                echo "macro read astrodepth_go_galfit.sm go_galfit_1" | "$AstroDepth_ScriptDir/sm" > "astrodepth_go_galfit_1.log"
-                # check output successful or not
-                if [[ ! -f "fit_1.fits" ]]; then 
-                    echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_1! Sorry!"
-                    echo "Log file: \"astrodepth_go_galfit_1.log\""; cat "astrodepth_go_galfit_1.log"
-                    exit 1
-                fi
-            fi
-            # 
-            echo "Done!"
+        # Check output name
+        if [[ $j -ge ${#AstroDepth_INP_OUTPUT_NAME[@]} ]]; then
+            AstroDepth_OutputName="astrodepth_image_${j}_galfit"
         else
-            echo "No catalog source within image! Skip and continue!"
+            AstroDepth_OutputName=${AstroDepth_INP_OUTPUT_NAME[j]}
         fi
         # 
-        cd "$AstroDepth_CurrrentDir"
-    fi
+        # 
+        # cd 
+        if [[ 1 == 1 ]]; then
+            # 
+            cd "$AstroDepth_OutputDir/$AstroDepth_OutputName/"
+            # 
+            # now we run galfit in sci image
+            if [[ ! -f "No_catalog_source_within_image" ]]; then
+                if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"galfit"* || ! -f "fit_0.fits" ]]; then
+                    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_0\""
+                    echo "macro read astrodepth_go_galfit.sm go_galfit_0" | sm > "astrodepth_go_galfit_0.log"
+                    # check output successful or not
+                    if [[ ! -f "No_catalog_source_within_image" && ! -f "fit_0.fits" ]]; then 
+                        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_0\"! Sorry!"
+                        echo "Log file: \"astrodepth_go_galfit_0.log\""; cat "astrodepth_go_galfit_0.log"
+                        exit 1
+                    fi
+                fi
+                if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"galfit"* || ! -f "fit_1.fits" ]]; then
+                    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_1\""
+                    echo "macro read astrodepth_go_galfit.sm go_galfit_1" | sm > "astrodepth_go_galfit_1.log"
+                    # check output successful or not
+                    if [[ ! -f "No_catalog_source_within_image" && ! -f "fit_1.fits" ]]; then 
+                        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_1\"! Sorry!"
+                        echo "Log file: \"astrodepth_go_galfit_1.log\""; cat "astrodepth_go_galfit_1.log"
+                        exit 1
+                    fi
+                fi
+                # 
+                echo "Done!"
+            else
+                echo "No catalog source within image! Skip and continue!"
+            fi
+            # 
+            cd "$AstroDepth_CurrrentDir"
+        fi
+        
+    done
     
-done
+fi
 
 
 
@@ -534,61 +601,61 @@ done
 # 
 # 
 if echo "${AstroDepth_INP_STEPS[@]}" | grep -q -i "gaussian"; then
-    echo ""; echo ""; echo ""
+    #echo ""; echo ""; echo ""
     echo "Continue further steps: gaussian"
-    echo ""; echo ""; echo ""
-else
-    exit
-fi
-# 
-# 
-for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
+    #echo ""; echo ""; echo ""
     # 
     # 
-    # Check output name
-    if [[ $j -ge ${#AstroDepth_INP_OUTPUT_NAME[@]} ]]; then
-        AstroDepth_OutputName="astrodepth_image_${j}_galfit"
-    else
-        AstroDepth_OutputName=${AstroDepth_INP_OUTPUT_NAME[j]}
-    fi
-    # 
-    # 
-    # cd 
-    if [[ 1 == 1 ]]; then
+    for (( j=0; j<${#AstroDepth_INP_IMAGE_SCI[@]}; j++ )); do
         # 
-        cd "$AstroDepth_OutputDir/$AstroDepth_OutputName/"
         # 
-        if [[ ! -f "No_catalog_source_within_image" ]]; then
-            if [[ ! -f "fit_2.fits" ]]; then
-                echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_2"
-                echo "macro read astrodepth_go_galfit.sm go_galfit_2" | "$AstroDepth_ScriptDir/sm" > "astrodepth_go_galfit_2.log"
-                # check output successful or not
-                if [[ ! -f "fit_2.fits" ]]; then 
-                    echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine go_galfit_2! Sorry!"
-                    echo "Log file: \"astrodepth_go_galfit_2.log\""; cat "astrodepth_go_galfit_2.log"
-                    exit 1
-                fi
-            fi
-            if [[ -f "fit_2.fits" ]]; then
-                echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine print_result_final"
-                echo "macro read astrodepth_go_galfit.sm print_result_final" | "$AstroDepth_ScriptDir/sm" > "astrodepth_print_result_final.log"
-                # check output successful or not
-                if [[ ! -f "fit_2.result" ]]; then 
-                    echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine print_result_final! Sorry!"
-                    echo "Log file: \"astrodepth_print_result_final.log\""; cat "astrodepth_print_result_final.log"
-                    exit 1
-                fi
-            fi
-            # 
-            echo "Done!"
+        # Check output name
+        if [[ $j -ge ${#AstroDepth_INP_OUTPUT_NAME[@]} ]]; then
+            AstroDepth_OutputName="astrodepth_image_${j}_galfit"
         else
-            echo "No catalog source within image! Skip and continue!"
+            AstroDepth_OutputName=${AstroDepth_INP_OUTPUT_NAME[j]}
         fi
         # 
-        cd "$AstroDepth_CurrrentDir"
-    fi
+        # 
+        # cd 
+        if [[ 1 == 1 ]]; then
+            # 
+            cd "$AstroDepth_OutputDir/$AstroDepth_OutputName/"
+            # 
+            # now we run galfit in sci image with Gaussian models
+            if [[ ! -f "No_catalog_source_within_image" ]]; then
+                if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"gaussian"* || ! -f "fit_2.fits" ]]; then
+                    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_2\""
+                    echo "macro read astrodepth_go_galfit.sm go_galfit_2" | sm > "astrodepth_go_galfit_2.log"
+                    # check output successful or not
+                    if [[ ! -f "fit_2.fits" ]]; then 
+                        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"go_galfit_2\"! Sorry!"
+                        echo "Log file: \"astrodepth_go_galfit_2.log\""; cat "astrodepth_go_galfit_2.log"
+                        exit 1
+                    fi
+                fi
+                #if [[ "${AstroDepth_INP_OVERWRITE[@]}" == *"gaussian"* || -f "fit_2.fits" ]]; then
+                #    echo "Running Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_final\""
+                #    echo "macro read astrodepth_go_galfit.sm print_result_final" | sm > "astrodepth_go_galfit_print_result_final.log"
+                #    # check output successful or not
+                #    if [[ ! -f "fit_2.result" ]]; then 
+                #        echo "Error! Failed to run Supermongo script \"astrodepth_go_galfit.sm\" subroutine \"print_result_final\"! Sorry!"
+                #        echo "Log file: \"astrodepth_go_galfit_print_result_final.log\""; cat "astrodepth_go_galfit_print_result_final.log"
+                #        exit 1
+                #    fi
+                #fi
+                # 
+                echo "Done!"
+            else
+                echo "No catalog source within image! Skip and continue!"
+            fi
+            # 
+            cd "$AstroDepth_CurrrentDir"
+        fi
+        
+    done
     
-done
+fi
 
 
 
