Updates

diff --git a/Softwares/do_Preset b/Softwares/do_Preset
--- a/Softwares/do_Preset
+++ b/Softwares/do_Preset
@@ -39,11 +39,13 @@ export DG_VARY=0
 export DG_PRIM=0 # PRIORMAG
 export DG_PARA=1 # PARALLEL
 export DG_PFIT=0 # fit full catalog? 0=fitAll 1=fitInclSubIncl 2=fitExclSubExcl
-export DG_FSED="" # "SED_predictions_goodsn_$1" # _$2
-export DG_FRES=""
-export DG_CATA="" # "RadioOwenMIPS24_priors_April18_2014.txt"
-export DG_CATB="none"
-export DG_NAME=""
+export DG_FSED="NONE" # "SED_predictions_goodsn_$1" # _$2
+export DG_FRES="NONE"
+export DG_CATA="NONE" # "RadioOwenMIPS24_priors_April18_2014.txt"
+export DG_CATB="NONE"
+export DG_FSCI="NONE"
+export DG_FRMS="NONE"
+export DG_FPSF="NONE"
 export DG_FLOG=$(pwd)'/log_'$1'_'$2'_'$3
 export DG_FPWD=`pwd` # Current Path
 # 
@@ -73,131 +75,210 @@ type sky2xy
 type xy2sky
 type CrabPhotAperPhot
 echo ""
-#
-if [[ $* == *-vary* ]]; then
-DG_VARY=1
-DG_FSED=$DG_FSED # "_vary"
-DG_FLOG=$DG_FLOG"_Vary"
-echo ; echo We are varying prior positions!
-fi
+
+
 # 
-if [[ $* == *-priormag* ]]; then
-DG_PRIM=1
-DG_FLOG=$DG_FLOG"_PriorMag"
-fi
+# Read inputs
 # 
-if [[ $* == *-parallel* ]]; then
-DG_PARA=1
-DG_FLOG=$DG_FLOG"_Parallel"
-echo ; echo We are doing parallel!
-fi
+while [[ $# -gt 0 ]]; do
+    
+    case "$1" in
+                     
+             "-vary") shift
+                      DG_VARY=1
+                      DG_FSED=$DG_FSED # "_vary"
+                      DG_FLOG=$DG_FLOG"_Vary"
+                      echo ; echo We are varying prior positions!
+                      ;;
+                      
+         "-priormag") shift
+                      DG_PRIM=1
+                      DG_FLOG=$DG_FLOG"_PriorMag"
+                      ;;
+                      
+         "-parallel") shift
+                      DG_PARA=1
+                      DG_FLOG=$DG_FLOG"_Parallel"
+                      echo ; echo We are doing parallel!
+                      ;;
+                      
+     "-postparallel") shift
+                      DG_PARA=2
+                      DG_FLOG=$DG_FLOG"_PostParallel"
+                      echo ; echo We are doing post parallel!
+                      ;;
+                     
+          "-catalog") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_CATA="$1"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+      "-catalog-inp") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_CATA="$1"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+      "-catalog-out") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              GALFIT_CATALOG_OUT="$1"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+      "-catalog-add") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_CATB="$1"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+      "-sedpredict"*) shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_FSED="$(echo $1 | sed 's/\.txt$//g')"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+         "-fitsname") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_FSCI="$(echo $1 | sed 's/\.fits$//g')"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+     "-fitsname-sci") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_FSCI="$(echo $1 | sed 's/\.fits$//g')"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+     "-fitsname-rms") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_FRMS="$(echo $1 | sed 's/\.fits$//g')"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+     "-fitsname-psf") shift
+                      while [[ $# -gt 0 ]]; do
+                          if [[ "$1" != "-"* ]]; then
+                              DG_FPSF="$(echo $1 | sed 's/\.fits$//g')"
+                          else break; fi; shift
+                      done
+                      ;;
+                     
+           "-fitall") shift
+                      DG_PFIT=0
+                      DG_FLOG=$DG_FLOG"_FitALL"
+                      ;;
+                     
+          "-fitincl") shift
+                      DG_PFIT=1
+                      DG_FLOG=$DG_FLOG"_FitIncl"
+                      ;;
+                     
+          "-fitexcl") shift
+                      DG_PFIT=2
+                      DG_FLOG=$DG_FLOG"_FitExcl"
+                      ;;
+                     
+          "-fitadds") shift
+                      #DG_CATB="Radec_of_new_priors.txt"
+                      DG_FLOG=$DG_FLOG"_FitAdds"
+                      ;;
+                      
+                   *) shift
+                   
+    esac
+done
 # 
-if [[ $* == *-postparallel* ]]; then
-DG_PARA=2
-DG_FLOG=$DG_FLOG"_PostParallel"
-echo ; echo We are doing post parallel!
-fi
-# 
-if [[ $* == *-catalog* ]]; then
-DG_CATA=`expr "$*" : '.*-catalog[a-zA-Z]* \([^ -]*\)'`
-fi
-if [[ x"$DG_CATA" != x"" ]]; then
-    if [ ! -f $DG_CATA ]; then
-        #echo ; echo Warning! Catalog file $DG_CATA not found!
-        #if [[ -f "/upgal/GOODSN/GalSED/GalSed_201412_avec24_diffAGN/$DG_CATA" ]]; then
-        #    echo ; echo We will copy the SED prediction file from "/upgal/GOODSN/GalSED/GalSed_201412_avec24_diffAGN/$DG_CATA"!
-        #    cp "/upgal/GOODSN/GalSED/GalSed_201412_avec24_diffAGN/$DG_CATA" .
-        #else
-        #    echo ; echo Error! Catalog file $DG_CATA does not exist! Abort!; exit 1
-        #fi
-        echo ; echo Error! Catalog file $DG_CATA does not exist! Abort!; exit 1
+if [[ x"$DG_CATA" != x"NONE" ]]; then
+    if [ -f $DG_CATA ]; then
+        echo ; echo "We are using catalog $DG_CATA"
+    else
+        echo ; echo "Error! Catalog file $DG_CATA does not exist! Abort!"; exit 1
     fi
-    echo ; echo We are using catalog $DG_CATA
 else 
-    echo ; echo Error! We have no catalog!; exit 1
+    echo ; echo "Error! We have no catalog!"; exit 1
 fi
 # 
-if [[ $* == *-fitsname* ]]; then
-DG_NAME=`expr "$*" : '.*-fitsname[a-zA-Z]* \([^ -]*\)' | sed 's/.fits//g'`
-if [ ! -f $DG_NAME.fits ]; then
-echo Error! Fits file $DG_NAME.fits does not exist! Abort!; exit 1
-else
-echo ; echo We are using map $DG_NAME.fits instead of the map in goFine.sm
-fi
-fi
-# 
-if [[ $* == *-fitall* ]]; then
-DG_PFIT=0
-DG_FLOG=$DG_FLOG"_FitALL"
-fi
-# 
-if [[ $* == *-fitincl* ]]; then
-DG_PFIT=1
-DG_FLOG=$DG_FLOG"_FitIncl"
-fi
-# 
-if [[ $* == *-fitexcl* ]]; then
-DG_PFIT=2
-DG_FLOG=$DG_FLOG"_FitExcl"
-fi
-# 
-if [[ $* == *-fitadds* ]]; then
-DG_CATB="Radec_of_new_priors.txt"
-DG_FLOG=$DG_FLOG"_FitAdds"
-fi
-# 
-if [[ $* == *-catalog-add* ]]; then
-DG_CATB=`expr "$*" : '.*-catalog-add* \([^ -]*\)'`
-if [[ "$DG_CATB" == "none" ]]; then DG_CATB="none"; fi
-fi
-# 
-if [[ x"$DG_CATB" != x"none" ]]; then
-    if [[ -f $DG_CATB ]]; then
-        echo ; echo We will fit additional objects in $DG_CATB!
+if [[ x"$DG_FSCI" != x"NONE" ]]; then
+    if [ -f $DG_FSCI.fits ]; then
+        echo ; echo "We are using map $DG_FSCI.fits instead of the map in goFine.sm"
     else
-        echo ; echo Error! Additonal catalog $DG_CATB does not exist! Abort!; exit 1
+        echo ; echo "Error! Fits file $DG_FSCI.fits does not exist! Abort!"; exit 1
     fi
 else
-    echo ; echo We do not set any additonal catalog!
+    echo ; echo "We do not set fitsname-sci and will use the default sci fits image!"
 fi
 # 
-if [[ $* == *-sedpredict* ]]; then
-DG_FSED=`expr "$*" : '.*-sedpredict[a-zA-Z]* \([^ -]*\)' | sed 's/.txt//g'`
-fi
-if [[ $DG_PFIT -gt 0 ]]; then
-    if [[ ! -f $DG_FSED.txt ]]; then
-        # echo ; echo Warning! SED prediction file $DG_FSED.txt not found!
-        # if [[ -f "/upgal/GOODSN/GalSED/GalSed_201412_avec24_diffAGN/$DG_FSED.csv" ]]; then
-        #     echo ; echo We will copy the SED prediction file from "/upgal/GOODSN/GalSED/GalSed_201412_avec24_diffAGN/$DG_FSED.csv"!
-        #     cp "/upgal/GOODSN/GalSED/GalSed_201412_avec24_diffAGN/$DG_FSED.csv" .
-        # else
-        #     echo ; echo Error! SED prediction file $DG_FSED.csv does not exist! Abort!; exit 1
-        # fi
-        echo ; echo Error! SED prediction file $DG_FSED.txt does not exist! Abort!; exit 1
+if [[ x"$DG_FRMS" != x"NONE" ]]; then
+    if [ -f $DG_FRMS.fits ]; then
+        echo ; echo "We are using map $DG_FRMS.fits instead of the map in goFine.sm"
     else
-        echo ; echo We are using SED prediction $DG_FSED.txt
+        echo ; echo "Error! Fits file $DG_FRMS.fits does not exist! Abort!"; exit 1
+    fi
+else
+    echo ; echo "We do not set fitsname-rms and will use the default rms fits image!"
+fi
+# 
+if [[ x"$DG_FPSF" != x"NONE" ]]; then
+    if [ -f $DG_FPSF.fits ]; then
+        echo ; echo "We are using map $DG_FPSF.fits instead of the map in goFine.sm"
+    else
+        echo ; echo "Error! Fits file $DG_FPSF.fits does not exist! Abort!"; exit 1
+    fi
+else
+    echo ; echo "We do not set fitsname-psf and will use the default psf fits image!"
+fi
+# 
+if [[ x"$DG_CATB" != x"NONE" ]]; then
+    if [[ -f $DG_CATB ]]; then
+        echo ; echo "We will fit additional objects in $DG_CATB!"
+    else
+        echo ; echo "Error! Additonal catalog $DG_CATB does not exist! Abort!"; exit 1
+    fi
+else
+    echo ; echo "We do not set any additonal catalog!"
+fi
+# 
+if [[ $DG_PFIT -gt 0 ]]; then
+    if [[ -f $DG_FSED.txt ]]; then
+        echo ; echo "We are using SED prediction $DG_FSED.txt"
         if [[ $DG_PFIT -eq 1 && x"$DG_CATB" == x ]]; then echo ; echo We are fitting included objects only!; fi
         if [[ $DG_PFIT -eq 1 && x"$DG_CATB" != x ]]; then echo ; echo We are fitting included objects and additional objects only!; fi
         if [[ $DG_PFIT -eq 2 && x"$DG_CATB" == x ]]; then echo ; echo We are fitting excluded objects only!; fi
         if [[ $DG_PFIT -eq 2 && x"$DG_CATB" != x ]]; then echo ; echo We are fitting excluded objects only!; fi #<TODO># adds
+    else
+        echo ; echo "Error! SED prediction file $DG_FSED.txt does not exist! Abort!"; exit 1
     fi
 else 
-    echo ; echo We will fit all catalog objects!
+    echo ; echo "We will fit all catalog objects!"
 fi
 # 
-echo ; echo We will log into $DG_FLOG.smlog
+echo ; echo "We will log into $DG_FLOG.smlog"
 # 
 # more -- checking files
-# if [[ ! -f "do_Cleans" ]]; then ln -fs "../do_Cleans"; fi
 if [[ ! -f "goFine.sm" ]]; then ln -fs "../goFine.sm"; fi
 if [[ ! -f "goSimu.sm" ]]; then ln -fs "../goSimu.sm"; fi
-# if [[ ! -f "goCorrectdf.sm" ]]; then ln -fs "../goCorrectdf.sm"; fi
-# if [[ ! -f "do_PostGalfit" ]]; then ln -fs "../do_PostGalfit"; fi
 # if [[ ! -f "run_image_util.sm" ]]; then ln -fs "../run_image_util.sm"; fi
 # if [[ ! -f "run_update_catalog.sm" ]]; then ln -fs "../run_update_catalog.sm"; fi
-# if [[ ! -f "${DG_FSED}.csv" ]]; then cp "../../CatalogDeblend/$DG_FSED.csv" .; fi
-# if [[ ! $DG_VARY -eq 0 ]]; then if [[ ! -f "${DG_FSED}_vary.csv" ]]; then cp "../../CatalogDeblend/$DG_FSED.csv" .; fi; fi
-# if [[ ! -f "astroPhot.sm" ]]; then ln -fs "/Users/dliu/Working/2014-CEA/Tool/Level_5_SciDataDiagram/supermongo_go/code/astroPhot.sm"; fi
-# if [[ ! -f "Radec_of_new_priors.txt" ]]; then ln -fs "/Users/dliu/Working/2014-CEA/Data/Level_3_SciData/GOODS-North/GOODSN_Catalog/Select_on_Reisudal/Radec_of_new_priors.txt"; fi
 # 
-# 
+
+
+
+
+
